version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    
  sympolyassignment:
    image: sympolyassignment
    container_name: sympolyassignment
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - mongodb
    environment:
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
      MONGO_HOST: "${MONGO_HOST}"
      MONGO_PORT: "${MONGO_PORT}"

    volumes:
      - ./docker-compose.yml:/app/docker-compose.yml
    command: ["poetry", "run", "uvicorn", "main:app" ,"--host" ,"0.0.0.0","--port","80", "--reload" ]


# No need to define the volume at the bottom since we're using a bind mount
