FROM python:3.11-buster

# Set the working directory in the container
WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy the current directory contents into the container at /app
COPY . .

# Install dependencies using poetry
RUN poetry install
